minimal_mistakes_skin: "default"

title: Jess Godfrey
description: Maps, geographic information analysis, spatial analysis, cartography and data storytelling
url: "https://jess-godfrey.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: Jess Godfrey

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
